### ISSUE TITLE
Build Fails for iOS

### ISSUE THREAD

**Issue by arausch335** [beeware/beeware#114]
**Describe the bug**
During tutorial 5 for iOS I tried to run the code `briefcase build iOS` and got a `** BUILD FAILED **` error. Specific message is `Undefined symbols for architecture x86_64`

**To Reproduce**
1. Type `briefcase build iOS` into the terminal

**Expected behavior**
Expected the build to be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/88348187/127919832-d968b99d-479f-42b0-9546-c7b694b85e05.png)
![image](https://user-images.githubusercontent.com/88348187/127919904-b3fd5ff2-0e15-41f5-b297-951b402adf27.png)

**Environment:**
 - macOS Big Sur 11.2.3
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: Not sure
   - Xcode: 12.5.1

**Additional context**
Everything else was fine up until here. I was able to create, build, run, and package for macOS but not for iOS. Have command line tools downloaded for Xcode.

**Comment by LinasNas** [comment]
I am experiencing the exact same bug. I tried reinstalling Xcode, brew, updating Big Sur to the latest version (11.5.1), opening the terminal with and without rosetta, but the bug remains. I am using a Macbook with M1 chip - unsure if that may be related to the problem.

**Comment by freakboy3742** [comment]
Thanks for the report. I think the problem is the new support package I published over the weekend; that package is the first to natively support M1 hardware. As a result, the iOS package includes libFFI - which is in the support package, but not in the iOS template.

As an immediate workaround, you can manually add libFFI to your Xcode project; I'll make the change to the iOS template as soon as I get a chance.

**Comment by freakboy3742** [comment]
Looks like I made the change, but didn't push the change to the public repository. I've done so now - apologies for the inconvenience!
