### ISSUE TITLE
macOS Template does not support 3.10 (briefcase-android-gradle-template.git)

### ISSUE THREAD

**Issue by mike5722** [beeware/beeware#139]
Going through Tutorials, on Tutorial 5 for creating Android app, I get this error: **Template does not support 3.10**

(beeware-venv) bigmac:helloworld mike$ briefcase build android

[helloworld] Generating application template...
Using app template: https://github.com/beeware/briefcase-android-gradle-template.git, branch 3.10
**Template does not support 3.10**
(beeware-venv) bigmac:helloworld mike$ python3 --version
Python 3.10.1
(beeware-venv) bigmac:helloworld mike$ briefcase --version
0.3.5

**Environment:**
 - Operating System: macOS 10.14.6 Mojave
 - Python version: 3.10.1
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: ? - should be current I just installed BeeWare on Thurs., Jan 13 2022

**Comment by mike5722** [comment]
Xcode version 11.3.1

**Comment by freakboy3742** [comment]
The error is exactly what it says on the tin - Briefcase doesn't support Android 3.10 at this point. This is because we need to spend some time porting Python 3.10 to Android; I made an initial attempt at a port, and discovered some merge problems. 

It would be worth adding a note to the tutorial the documentation that the latest Python may not be supported, especially on mobile platforms.

**Comment by freakboy3742** [comment]
There's also room to modify Briefcase to improve the way this error is reported - "template does not support..." doesn't immediately suggest "this Python version isn't supported".

**Comment by mike5722** [comment]
Well, that's obvious now that you mention it. Guess I didn't expect that.
Thanks for the clarification!
In the meantime, should I try installing an earlier version? 3.9.? or 3.8.?

**Comment by freakboy3742** [comment]
Any version from 3.6 to 3.9 should be fine.

**Comment by freakboy3742** [comment]
Closing as we now support 3.10.
