### ISSUE TITLE
Alternative to Android Studio for beeware-android developers

### ISSUE THREAD

**Issue by alvindera97** [beeware/beeware#15]
I've been trying to seriously start with beeware especially on the android side of things. I understand that java, android-sdk an emulator, etc are perquisites to use beeware to develop android applications using python. 

**I would love to contribute to this project but the process to get anything reasonable on android is daunting. I am trying to find a comfortable alternative to android studio!**

Why?

1. _I do not code in Java or any other android development language so the IDE is almost useless to me from the coding/productivity point of view._

2. _The main requirements are android-sdk and java. I already have an IDE preferentially developed for python and I wouldn't be needing anything else._

3. _Android Studio's size is not convenient for any form of priority to be given to a software that I would barely be using to 20% capacity._

### In light of the reasons stated above, I would like to know exactly what is needed. 

1. **What version of java is most preferably required for android development with beeware on a linux machine? [preferably ubuntu 18.0.4LTS]**

2. **Would Python 3.6.7 (default, Oct 22 2018, 11:32:17) work together with beeware's tools to get android development operational (at least test-wise) together with the recommended java version?**

These questions are very important to me. I wasn't able to get direct instructions concerning the android development curve or alternatives to android studio. I have no problem with the IDE but I believe that **the major reason Android Studio is recommended** is for it automatic install of an emulator and android-sdk (GUI style).

I wouldn't practically call this an issue or a bug report but I didn't know any other way to reach the moderators of this great project.

I love python! And I would love to contribute to the python community!
I hope a favorable reply!

**Comment by freakboy3742** [comment]
Hi Nwokolo,

Thanks for getting in touch.

You're correct that BeeWare doesn't use *most* of Android studio. The 
only reason it's recommended is to simplify the "getting started" 
process. Google doesn't provide easy (or consistent over time) download 
URLs for "just the Android Developer Kit" - and when you *can* find such 
a URL, they don't provide clear instructions for how to *configure* 
those tools - I have found configuring a working Android emulator 
without using Android Studio has proven extremely difficult.

I agree that this is a lot of overhead - and, like you, I don't actually 
use Android Studio for any of my actual Android development. However, 
I've found it the single easiest way to get started, and the easiest way 
to resolve configuration problems when they occur. Often, the problem is 
something like a license not being agreed to - finding out which one 
from the command line is extremely difficult, but if you open Android 
Studio, you'll be almost immediately presented with a dialog box to 
approve the license that has been preventing progress. And, there are 
some configuration tasks for which I haven't been able to find a working 
command line invocation, but there's a simple "configure with defaults" 
button in Android Studio that works (the emulator is a good example here).

So, what is actually required for BeeWare development?

* Any Java SDK (anything after Java 6 should be fine)

* A full Android SDK for a recent version of Android

* A working Android emulator configuration.

* A Python 3.5 or 3.6 install.

That said - the Android backend for BeeWare is currently in a badly 
broken state. If you try to deploy an Android project, you'll get "DEX 
errors" - that's an error from the compiler that converts the Java JAR 
files produced by BeeWare into the internal format used by Android.. So, 
even if you *did* have all the Android developer tools, you'd have 
difficulty getting a project to run.

I'd very much like to simplify the Android development story, and 
minimize the size of any downloads required to get the examples working 
- if possible, automating as much of that process as possible - but my 
first priority has been getting the code to work *at all*.

You're more than welcome to help out; at the moment, tracking down the 
source of these DEX errors is the primary problem we're trying to solve. 
That work is all part of the VOC project at present; we've got a 
contribution guide in the docs if you want to try your hand at 
contributing there.

Yours,

Russ Magee %-)

**Comment by alvindera97** [comment]
Wow.... Well said. I completely agree with you. Getting android-sdk and an emulator to work is a bit of a pain without android studio. Thank you for the brisk reply. Before the end of the day, I should get my act together and just install Android Studio. As for the DEX errors, I'll be sure to investigate that. Thanks again. I'll be closing this [issue] as you've answered all the questions I asked. 

Long Live Python! Long Live Beeware!
