### ISSUE TITLE
Unable to install dependencies. This may be because one of your dependencies is invalid, or because pip was unable to connect to the PyPI server.

### ISSUE THREAD

**Issue by chuiliuyiyi** [beeware/beeware#171]
**Describe the bug**
python3.8 -m briefcase new    a helloword project
cd  helloword
python3.8 -m briefcase create android
Report error
Unable to install dependencies. This may be because one of your
dependencies is invalid, or because pip was unable to connect
to the PyPI server.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75259241/190060230-f9ca5af0-4068-4d0f-9980-66c72be0f80b.png)

**Environment:**
 - Operating System:
 - Python version:python3.8.3
 - Software versions:windows10
   - Briefcase:
   - Toga:
   - ...

**Additional context**

**Comment by freakboy3742** [comment]
I have no idea what you've done here, but your project is trying to install 3 different versions of toga. Can you share the contents of your `pyproject.toml` file? 

Also - can you share the briefcase error log file, rather than a screenshot? The screenshot only contains a small amount of the overall context - the log file generated by Briefcase contains a lot more useful information.

**Comment by freakboy3742** [comment]
Closing due to lack of response.
