### ISSUE TITLE
Suggestion for webapp example in the docs

### ISSUE THREAD

**Issue by auwsom** [beeware/beeware#173]
Hello, I just found Briefcase and it looks great. I skipped to the end of the tutorial to see if it has webapp capabilities to create the "hexafecta" of platforms and saw "Coming Soon". No worries, I just wanted to mention the Python package called FastAPI that I just used in the tutorial below to stand up a webapp in minutes using a very sparse amount of code. Perhaps this might help filling in the Docs for webapps.

https://github.com/andreRibeiro1989/medium/blob/main/chatbot/README.md
https://towardsdatascience.com/develop-a-conversational-ai-bot-in-4-simple-steps-1b57e98372e2

**Comment by freakboy3742** [comment]
Thanks; but that suggestion doesn't really help here.

The goal of the web step of the tutorial isn't "write a web app quickly" - there are dozens of tutorials for doing that, using Django, Flask, FastAPI, and others. Rather, the goal is to take the same source code that has been used in the first steps of the tutorial, run *the same code*, and generate a web app with the same behavior.

Although we haven't updated the tutorial yet, it is possible to do this today - Toga and Briefcase have support for web deployment backend. I'm hoping we'll be able to update the tutorial to include this extra step in the near future.

**Comment by auwsom** [comment]
@freakboy3742 
Great, thats awesome. Does Toga use one of those mentioned tools, or was it written from scratch? Really good to know, I may try to do that. 

Quick question.. are there any toolsets you know of that cross-compile Python like Golang does (maybe even a wrapper to golang with mypy for typing?) I've seen some tools like [bazel-zig-cc](https://discuss.python.org/t/towards-standardizing-cross-compiling/10357/30) and [cross-env](https://discuss.python.org/t/how-to-cross-compile-python-modules/8737). Many use Cython in some fashion.

This issue below was closed, but it doesnt seem that Breifcase cross-compiles.
Is there a more efficient way to implement BeeWare? https://github.com/beeware/beeware/issues/84

I'm just trying to survey the current options before getting invested into a particular path. Thank you.

**Comment by freakboy3742** [comment]
Toga doesn't involve a web server at all. it uses PyScript to get a client-side Python interpreter, and renders what is effectively a "single page app". 

Briefcase formalises the packaging process and rendering into a HTML to load that page. It provides a simple web server for debug purposes, but the content generated by Briefcase could be served by any web server.

I have no idea what is going on with the ticket you've referenced; the user who opened it, closed minutes after it was opened. However, I'm not sure what they're trying to achieve with compiling in the form they describe - it won't actually speed anything up. Cython isn't "magical speed juice" - it has very specific situations in which it will make things faster. 

More generally, what are you actually trying to do when you say "cross compile"? The two links you've provided are two completely unrelated use cases, so it's not clear what it is you're actually trying to achieve.

**Comment by auwsom** [comment]
@freakboy3742 thanks for your reply..

Basically, I want the broadest reach possible for an application. It seems like Electron is the popular tool, maybe it does actually cross-compile to the big 3 OS platforms, and there are tools for mobile apps, but it uses html for the user interface. That makes using as a webapp easy, but adds size to the mobile apps. 

Golang can do actual cross-compiling to the big 3 (without needing to run them), and results in very compact and efficient applications. It can also target ios, android and arm, etc. It seems if apps were written in exclusively Cython compatible code, the cross-compilation could be similar to Golang. Afaik, the Python packagers (like Appimage) include the entire Python interpreter (probably how Briefcase does .app and msi).

So I'm trying to figure out if there exists other tools that do cross-compilation like Golang. The first link discussed exactly that. The second one discussed cross-env, a tool I havent heard of. But I did find the one I was thinking of called [Nuitka.](http://nuitka.net/) In the SO page below, the top answer discusses the "freeze" strategy which packages the entire python interpreter versus Cython and Nuitka (which I just learned doesnt do  [cross-compilation yet)](https://github.com/Nuitka/Nuitka/issues/43). The latter does however "executes uncompiled code and compiled code together in an extremely compatible manner" [link](https://github.com/Nuitka/Nuitka). Taking care of packages that are not Cython compatible.

https://stackoverflow.com/questions/12059509/create-a-single-executable-from-a-python-project

So, I'm not looking for magical "speed-juice" so much as magical interoperability, unification and standardization. It does look like the path would be Cython or Nuitka > bazel-zig-cc. I figured since this project is in the related field, you all might know the state of the art on this matter. Thank you

**Comment by freakboy3742** [comment]
So - I still don't entirely understand what you're trying to do. You've mentioned a bunch of different technologies, but they're all solving different problems in different ways - and none of them are related to the "web app" that was the start of this discussion.

Briefcase is a tool for producing the type of application that end users of desktop and mobile operating systems are familiar with - the sort of app that appears on a Start menu or Launchpad, presents as an icon that is clicked, and has a GUI. Briefcase is able to take a body of Python code that displays a GUI, and package it for macOS, Windows, Linux, iOS, Android and the web. Briefcase solves the problem of getting a standalone Python interpreter and code onto the user's computer in a way that means the end-user doesn't have to care about the fact that they're running a Python interpreter.

Cython doesn't make an application "cross platform". It provides a way to produce optimised code modules. It's a way to make a computationally intense loop faster by giving hints to the code that CPU-optimized instructions can be used. It still requires you to compile the module for every target platform where you want the code to run.

cross-env solves a completely different problem again - it provides a way to compile C modules for a platform other than the platform you're currently on. This doesn't normally matter for Python; but it's critical if you're dealing with iOS or Android because you can't (or don't) run a C compiler *on* those platforms. 

Go is solving a different packaging problem. It doesn't produce GUI apps - it produces command line apps. It produces a single binary, because that's the style of tool it's targeting. You can probably use Go to produce a GUI app - but you'll need to use some other tool to handle the rest of the "App packaging" problem that lets a binary appear as an app on a Launchpad. Nuitka is roughly analogous here; there are certain modes of operation of PyInstaller that are also similar.
 
Electron is a different tool again. It is effectively a GUI framework - a way of making a GUI for an app using HTML+JS. You still need to work out how to package and distribute your application for distribution.

You keep using the words "Cross Compilation"... but your usage of that phrase doesn't map onto any usage that I'm familiar with. Cross compiliation is using a Windows machine to produce a macOS binary. That will be, at the very least, difficult, because the tools needed aren't cross platform. Xcode is only available on macOS. Visual Studio is only available on Windows. I'm sure someone who is sufficiently motivated can make that work... but why would you bother? After you've cross compiled your Windows app on macOS... you won't be able to test it - so you'll need to seek out a Windows machine to test on. If the issue is having availability of development machines on which to do compilation: GitHub Actions provides CI environments that lets you build native binaries on any platform you want. Go is able to do this because the Go compiler and standard library is an ecosystem unto itself - but the side effect is that the apps are usually only command line apps.

And none of this has anything to with web apps, which is where this thread started.

So - once again: What are you actually trying to do? What *specific problem* are you trying to solve? It's very difficult to advise whether BeeWare is a good match for your use case when all you're telling me is the selection of wildly unrelated technologies you're considering. If you can tell us what your actual end use-case is, we might be able to provide advice.

**Comment by auwsom** [comment]
@freakboy3742 great, thanks again..

First, good points regarding Go being mostly CLI. In fact, that explains a bit of why other platforms arent strictly necessary to test and debug on. And thanks for pointing me towards that GitHub Actions feature. 

I am envisioning not testing GUI apps on some platforms. I'm not going to buy an iPhone or a Mac to test on unless the success of the application warrants it. Users of proprietary platforms have to accept that barrier for devs, but thats another story. 

The speed of Cython is almost irrelevant to me compared to the cross-platform compilation it allows through C. Yes, I mean cross-compilation. I'm developing a webapp that I want available on mobile and keep options open for desktop platforms. So that's why I started asking about webapps. Electron would work, but Python is important to me, so I landed here. I did just find a page discussing translating Python to JS with [Transcrypt](https://github.com/QQuick/Transcrypt), and it looks like Capacitor is the popular mobile side of Electron. It connects to native mobile APIs and doesnt need to be as large as Electron. Briefcase still interests me for being able to stay in Python (it is amazing intrinsically). If it can create a mobile app and a web app with the same code, that is excellent. 

I'm trying to distill these technologies down to some common denominators. Cross-compilation of GUI apps may be asking too much. I appreciate your replies. 

I guess I need to compare the Briefcase web and mobile apps, with Electron and Capacitor either with JS or using Transcrypt. Could you share the code for your or an example Briefcase web app?

**Comment by freakboy3742** [comment]
So - I have literally just walked off stage at DjangoCon US where I discussed this specific use case - wrapping a web app as a native app. And I can point you at an example: the Toga examples folder contains two examples: positron-static and positron-Django, which generate an Electron-style "app" whose GUI is a web app that is served internally.

Using Briefcase to target the web is a different approach: it uses Pyscript to treat the web browser as a native platform.
