### ISSUE TITLE
Beewrre Tutorial Step 5: can't find folder

### ISSUE THREAD

**Issue by gelbelle** [beeware/beeware#198]
### Describe the bug

I've been following your tutorial as recommended prior to contribution. It all ran wonderfully until I got to the part about mobile devices. Since I'm on Linux I picked Android. When I ran `briefcase create android` I received an Errno 20 Not a directory. I received the errors in the log file below.

It seems to have something to do with my jdk. I did find some threads online about issues with OpenJDK but they were a few years old. I just installed the latest JDK for Ubuntu 22.04 last week.
```angeleah@angeleah-X580VD:~$ java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-Ubuntu-0ubuntu322.04)
OpenJDK 64-Bit Server VM (build 19.0.2+7-Ubuntu-0ubuntu322.04, mixed mode, sharing)
```

### Steps to reproduce

Type `briefcase create android `within the `beeware-tutorial/helloworld` virtual environment.

### Expected behavior

I expected it to create as it did when I just ran `briefcase create`

### Environment

- Operating System: Ubuntu 22.04
- Python version: Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
- Software versions:
  - Briefcase: (beeware-venv) angeleah@angeleah-X580VD:~/Documents/Dev/beeware-tutorial/helloworld$ briefcase -V
0.3.13
  - Toga:  Not sure how to find this. I followed the tutorial and there was no install toga part, but the tutorial worked until Step 5.
  - ...

### Logs

[briefcase.2023_03_20-15_24_38.create.log](https://github.com/beeware/beeware/files/11023709/briefcase.2023_03_20-15_24_38.create.log)

**Comment by freakboy3742** [comment]
It looks like we've got to the bottom of this (or, at least, we've been able to replicate it) - For some reason, your `JAVA_HOME` is pointing to the java binary, rather than root of the java install (which is what `JAVA_HOME` should point at). We've just added some extra protection to Briefcase to catch this edge case, but the immediate fix for you is what I said previously - unset the `JAVA_HOME` variable, then re-run the problem `briefcase` command.
