### ISSUE TITLE
exec()

### ISSUE THREAD

**Issue by Clear-Lake** [beeware/beeware#211]
### Describe the bug

![image](https://user-images.githubusercontent.com/96899001/233837301-10596e45-293c-42e8-bb49-e35b4484793f.png)
![image](https://user-images.githubusercontent.com/96899001/233837306-fbd01605-ac6a-4b59-ab01-b56b9b88bc87.png)
![image](https://user-images.githubusercontent.com/96899001/233837340-f6e962a9-bbe5-4b79-a1a5-365b1b6c1730.png)
I want to create a lot of variables 
![image](https://user-images.githubusercontent.com/96899001/233837530-0dfafe04-1566-4ba2-a707-c1eff9d5a9da.png)
but i can't

### Steps to reproduce

Windows+R
cmd
enter
briefcase new
enter
enter
enter
.....
src/helloworld/app.py
`
![image](https://user-images.githubusercontent.com/96899001/233837735-9b867506-f56e-4a97-8766-9b561b9699ce.png)
`
cmd
cd helloworld
briefcase dev
error

### Expected behavior

![image](https://user-images.githubusercontent.com/96899001/233837783-ba8c1148-71c1-4693-9819-71fd6f4da732.png)

### Environment

- ![image](https://user-images.githubusercontent.com/96899001/233838091-ca0a5c7f-ec67-4971-8071-d934a572fab3.png)
- 
![image](https://user-images.githubusercontent.com/96899001/233838054-b771bed6-846c-4eba-be7a-6ff8da0b1182.png)

- Software versions:
  - Briefcase:
![image](https://user-images.githubusercontent.com/96899001/233838506-3bbe0c9c-a658-404a-b268-3c242760d347.png)

  - Toga:
  - ...
![image](https://user-images.githubusercontent.com/96899001/233838504-8907930c-9483-49d8-ae9a-24c0b9eba092.png)

### Logs

```

```

**Comment by freakboy3742** [comment]
So - this isn't a bug; but it's complex side effect of interpreter optimisation. As a result of using `exec()`, the `asdf` symbol isn't obviously in the locals, and as a result, the variable lookup is being optimised in a way that causes an error.

`print(locals()["asdf"])` will work, because it's doing a dynamic runtime lookup in the locals dictionary.

That said: using `exec` in code is almost always a bad idea, as it's a massive security risk. There are much better ways to achieve what you're done here.

Here's 3 better ways to create instances in a loop:

1. Add the object directly to `locals()`: `locals()[i] = toga.Label(...)`
2. Assign the values as attributes of the app: `setattr(self, i, toga.Label(...))`
3. Use a dictionary to store your instances: 
```
labels = {}
...
labels[i] = toga.Label(...)
```

Of these, (3) is the one I'd recommend, as it's the most direct approach.

**Comment by Clear-Lake** [comment]
thx

**Comment by Clear-Lake** [comment]
![image](https://user-images.githubusercontent.com/96899001/233914533-09686ce1-66c7-4e62-8c5b-92a61879f7e2.png)
![image](https://user-images.githubusercontent.com/96899001/233914596-7acdb12b-d015-472a-b35a-e9d757ee4b55.png)
emmm...help

**Comment by freakboy3742** [comment]
If those are the only 3 lines of code, then you're trying to set a dictionary key on a local dictionary called `labels`, then a key on a dictionary stored as a class attribute named `labels`. However, you haven't shown the line where you *define the dictionary*. In the example code I provided `labels = {}` is a critical piece - you need to define the dictionary before you can use it.
