### ISSUE TITLE
vicious documentation circle while trying to get basic briefcase tutorial

### ISSUE THREAD

**Issue by yarikoptic** [beeware/beeware#238]
### Describe the bug

documentation just keeps going in circle across a few links/pages whenever user tries to discover how to use briefcase

### Steps to reproduce

1. Go to https://github.com/beeware/briefcase/
2. If you want to see Briefcase in action, try the [BeeWare tutorial](https://beeware.readthedocs.io/).
3. [Briefcase](https://briefcase.readthedocs.io/), a tool for packaging Python projects as distributable artefacts that can be shipped to end users;
4. [Tutorial](https://briefcase.readthedocs.io/en/stable/tutorial/index.html#tutorial)
5. [The BeeWare tutorial](https://docs.beeware.org/en/latest/) walks you through the process of building a native Python application from scratch.

and end up on result of step 2 - 3.

### Expected behavior

get to Briefcase tutorial

### Environment

N/A

### Logs

```

```

**Comment by mhsmith** [comment]
There are links to the actual tutorial at both the bottom and the left of https://docs.beeware.org/en/latest/.

However, I agree that the two links that say "BeeWare tutorial" should go directly to the tutorial rather than the docs front page.

**Comment by freakboy3742** [comment]
I'm confused - what I'm seeing isn't matching what has been described here.

If I go to https://github.com/beeware/briefcase/, it says "try the [BeeWare tutorial](https://beeware.readthedocs.io/).". That *is* the BeeWare tutorial - you're already on the page that you arrive at again on step 5. https://beeware.readthedocs.io and https://docs.beeware.org are the same site (the latter is aliased to the former).

Yes, the page you land on at step 2 does contain a link to the documentation for Briefcase and Toga. Those links are provided in the context of describing what BeeWare *is*, prior to the call to action "Ready to try BeeWare for yourself? Let’s build a cross platform application in Python!". From a project perspective, this is an important page - BeeWare is a collection of tools, not a single tool. This page is an important preamble; we can't just skip to the "Tutorial 0" page without losing some important background information.

So - I'm not sure I understand which link (or links) should be updated to point where. The closest I can come to a "fix" for this bug would be to alter the text on https://docs.beeware.org to make it clear that you've landed on a tutorial... but I'm not sure if I've correctly understood the source of the confusion.

**Comment by mhsmith** [comment]
I think the problem with https://docs.beeware.org/ is:
* The full tutorial link list on the left is collapsed on smaller screens.
* That only leaves the link at the bottom, which isn't very prominent with all the stuff above it.

I guess it is important to give the user some general context of what BeeWare is, but I think we can reduce the text quite a bit:
* Remove the paragraph about "[software development tools](https://beeware.org/project/projects/tools/) and [applications](https://beeware.org/project/projects/applications/)", because most of them are not being actively maintained, and they're not relevant to the tutorial anyway.
* Remove the sentence about "set top boxes and watches", because that isn't going to happen in the near future.
* Remove the "work in progress" box, because all platforms have pretty good support now, except for the web, which already has a warning box on its own page.
