### ISSUE TITLE
Error:   pip install --pre beeware

### ISSUE THREAD

**Issue by BonemyGUY** [beeware/beeware#25]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\bonemy\beeware-tutorial\beeware-venv\scripts\python.exe'
 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Bonemy\\App
Data\\Local\\Temp\\pip-install-_iyuk3o7\\pythonnet\\setup.py'"'"'; __file__='"'"
'C:\\Users\\Bonemy\\AppData\\Local\\Temp\\pip-install-_iyuk3o7\\pythonnet\\setup
.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repla
ce('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exe
c'"'"'))' egg_info --egg-base 'C:\Users\Bonemy\AppData\Local\Temp\pip-install-_i
yuk3o7\pythonnet\pip-egg-info'
         cwd: C:\Users\Bonemy\AppData\Local\Temp\pip-install-_iyuk3o7\pythonnet\

    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Bonemy\AppData\Local\Temp\pip-install-_iyuk3o7\pythonnet\se
tup.py", line 18, in <module>
        from wheel import bdist_wheel
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.

**Comment by freakboy3742** [comment]
Thanks for the report! 

I can tell you're on Windows; it would be helpful to know what version of Python you're using - I'm guessing you're using Python 3.8.

If this is correct, then the problem you've reported is being cause because there's no pre-compiled version of Python.net available for Python 3.8, and installing Python.net from source is a complicated matter. 

There's not a whole lot *we* can do to address this; we're dependent on upstream packaging here. However, we can definitely add a note to the tutorial warning about this problem if it occurs.
