### ISSUE TITLE
error: ModuleNotFoundError: No module named 'gitdb.utils.compat'

### ISSUE THREAD

**Issue by joelfreybott** [beeware/beeware#31]
Got this error many times. 
It appeared during your "tutorial 0" when I tried "briefcase new". No errors until then.
Installing the packages again did not help.
OS: Linux Mint 19.3

Full line: 
/beeware-tutorial/beeware-venv/lib/python3.6/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'

**Comment by freakboy3742** [comment]
@joelfreybott Thanks for the report! 

As it happens, I actually know the source of this error, but for reasons unrelated to Briefcase. 

Last week, gitdb2 published a new major version. gitdb2 is a dependency of GitPython; and GitPython is a dependency of Briefcase.

Unfortunately. GitPython doesn't specify it's version dependency in a way that protects against the major version update in gitdb2.

Making matters worse, Briefcase specifies GitPython==3.0.2 - a version that *isn't* compatible with the new version of gitdb2.

As an immediate fix, if you manually update the version of GitPython that is installed in your briefcase virtual environment:
```
$ python -m pip install -U GitPython
```
you won't get the error any more. 

I've got a fix for this in #301; I'll push out a new release shortly so that others aren't affected.

**Comment by freakboy3742** [comment]
I've just pushed Briefcase v0.3.0.dev6 to correct this problem.

Thanks again for the report, and apologies for the confusion!

**Comment by joelfreybott** [comment]
Thank you so much for the fast answer and immediate fix!
Amazing!

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.
