### ISSUE TITLE
Improving linux scaffolding instructions

### ISSUE THREAD

**Issue by daonb** [beeware/beeware#44]
I've just went through the tutorial and they're great.  The only thing I believe can be improved is the section that talk about creating the scaffolds on linux. The tutorial gives 4 options and while the instructions are complete I found them to be too detailed for a tutorial.

I would be happy to update the docs so we keep the option of building on my machine, explaining its limitations - supporting only mine and newer libc - and add a link to an How To guide in briefcase docs. This guide should explain the libc limitations and provide the instructions for building it in a docker or adding it as a git hub action.

**Comment by freakboy3742** [comment]
I agree that there's the amount of detail in the current version is a little overwhelming. 

Breaking this into a simpler "just get it working" configuration, with more detail in a howto is also an interesting idea. However, I don't think it's as simple as you suggest.

The problem is that the default support library *only* works on Ubuntu 16.04 - so we'd need to add steps on how to build your own support library, and then add a reference to that support library in the configuration file. This is *possible* but definitely a lot more work than I'd generally expect a novice developer to perform. 

The other approach is to tackle this at a technological level. It would be possible to modify Briefcase to use Docker directly. This way we could always guarantee that Ubuntu 16.04 (or suitable analog) is available. I've opened beeware/briefcase#44 to track this specific feature.

If you've got any ideas on other ways to simplify the tutorial, or ways to avoid the manual support package requirement, I'm open to suggestions.

**Comment by daonb** [comment]
I agree that the best place to solve this is at the technological level. I'll try and find the time to work on the briefcase case you mentioned.
