### ISSUE TITLE
Physical Device not detected while using briefcase run android

### ISSUE THREAD

**Issue by alok29awasthi** [beeware/beeware#88]
**Describe the bug**
I connected my laptop to my mobile (in developers mode) and tried running `briefcase run android`. But it does not show up any physical device. My laptop does not have a UEFI mode, it is in Legacy mode. In case, this is the issue then please include a turnaround way for this. Also, I had to install Android studio for using the emulator and work using 'arm' as it is the only one that works with Legacy mode. Can you add some of the ways that people with different sets of system configuration can work through the tutorial.

**Expected behavior**
My device is detected using the `briefcase run android` or any other way to use my device for demo checking of the app.

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.6.4

**Comment by freakboy3742** [comment]
Briefcase isn't doing anything special here - we are 100% dependent on the capabilities of the underlying Android tools. If ADB can't detect your device, there's nothing Briefcase can do about it.

I'm not especially enthused about adding support for Legacy mode, as doesn't lead to a particularly good developer experience. Realistically, Android development requires relatively modern hardware; I would rather *not* provide support than provide a bad developer experience.

That said - we're definitely open to improving detection of platforms that won't be supported, or at the very least improving the documentation of the prerequisites. If anyone wants to research and document those requirements, we'd be glad to add that to the tutorial.

Marking this ticket as an enhancement on that basis.

**Comment by freakboy3742** [comment]
On reflection, this appears to be an issue with supporting old developer hardware. While I'd very much like to be able to support old hardware, Google itself doesn't appear to share that commitment, which binds our hands. 

Closing on the basis that it, in practical terms, this issue is unlikely to remain unaddressed. However, if someone wanted to investigate and provide a Briefcase patch to support older hardware configurations, we'd gladly consider that patch.
