### ISSUE TITLE
Where are beeware files installed?

### ISSUE THREAD

**Issue by Harry-Garrison** [beeware/beeware#91]
Hello!

This project seems very interesting and all, but the downside is that the files needed to create an executable are too big. I am referring mostly to Android, which requires a lot of files in order to compile an app. I would like to uninstall all the android components from my PC due to space constraints, but I cannot seem to find where they have been installed. I deleted the android folder from my Python folder, as well as gradle and android studio. However, I still have a few more gigabytes to delete and I can't find them. When beeware downloads jdk, for example, where is it downloaded? How can I find all beeware components and delete the ones I do not currently need?

**Comment by Harry-Garrison** [comment]
Nevermind, I found it! Everything i included in a folder named .briefcase in C:\Users\User\.briefcase

**Comment by freakboy3742** [comment]
Everything that Briefcase downloads as part of the build process is contained in the `.briefcase` directory within your user's home directory. (i.e., `~/.briefcase` on macOS and Linux; `C:\Users\<your username>\.briefcase` on Windows).

Closing the ticket since the question should be answered; if you need any more details, feel free to keep the discussion going here, or open a new ticket.
