### ISSUE TITLE
Apps with Multiple Views 

### ISSUE THREAD

**Issue by HugHunter** [beeware/beeware#92]
I don't think this has been properly answered before, but I have seen a few questions on StackOverflow asking whether it is possible to set up multiple views which can be accessed through a button click for example. 

Is this a 'feature' that already exists but not documented or something that will be added in the future?

**Comment by freakboy3742** [comment]
What exactly do you mean by "Multiple views"? 

Do you mean Windows? In which case - it's not explicitly documented... but it does exist. You can create as many windows as you want - you just create an instance of Window, assign content to it, and call `window.show()`. The decision of when to display that window is entirely up to you as the programmer, so it can be in response to a button press, menu selection, or whatever else you want.

If you mean something else, please provide more details, and I'll do what I can to help.

**Comment by HugHunter** [comment]
Yes, sorry! Coming from iOS development, where they are called views haha
Alright, thank you

I seem to struggle with getting a second window showing.. Do I define a second function like below?

`def second_window(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        #button
        button = toga.Button(
            'Test',
            on_press = self.say_hello,
            style=Pack(padding=5)
        )

        #loading widgets
        main_box.add(button)

        self.main_window = toga.Window(title='Test')
        self.main_window.content = main_box
        self.main_window.show()`

**Comment by HugHunter** [comment]
Yes, sorry! I just came from and iOS project, where they are called views haha

I seem to struggle with getting a second window showing. Do I define a second function like below?
```
def second_window(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        #button
        button = toga.Button(
            'Test',
            on_press = self.say_hello,
            style=Pack(padding=5)
        )

        #loading all widgets
        main_box.add(button)

        self.main_window = toga.Window(title='Test')
        self.main_window.content = main_box
        self.main_window.show()
```

**Comment by freakboy3742** [comment]
Ah - my misunderstanding - you're on a mobile platform, and looking for richer navigation views (e.g., a "stacks" of content views, with panels that slide left/right to reveal new content). 

That's a feature that is not currently implemented. We definitely *want* to add navigation views; A tab-like OptionContainer will likely be the first one added, but we also want to implement tree navigation and table detail navigation. Unfortunately, I can't give an ETA, as this is a volunteer project, so our rate of progress is entirely determined by community contributions. If you're interested in contributing, this would be a great place to do so.

The multiple window technique I described only works on desktop platforms, and generates entirely standalone windows, rather than providing a navigation mechanism in a single window.

I'm going to close this ticket as the original question has been answered, and we're not currently using tickets to track features that are on our roadmap. If you have any follow-up questions, feel free to continue the conversation here, or open a new ticket.
