### ISSUE TITLE
helloworld runs fine on dev mode but on on run mode

### ISSUE THREAD

**Issue by m1233** [beeware/beeware#97]
For some reason my program runs fine on dev mode but not in run mode

I just started using beeware and have been following the tutorial series on beeware's site. I have followed the tutorial step by step but when I type "briefcase run" I get an error saying "Unable to start app HelloWorld". I found that more people had the same problem in some of their own projects and they didn't find a solution. I am doing this on windows 10 and using python 3.5.4.

![Στιγμιότυπο οθόνης (165)](https://user-images.githubusercontent.com/38630937/106354553-6245ff80-62fb-11eb-8ed8-68b8e5596d61.png)

**Comment by freakboy3742** [comment]
Thanks for the report, and sorry to hear you're having problems. 

To confirm - is this the stock BeeWare tutorial that is failing, or is there additional code that you've added? When this problem has occurred for others, it's almost always because of a dependency that has been added to the code and the dev environment, but hasn't been added to `pyproject.toml` as a requirement. 

The second cause is when a third party dependency has been added, but that dependency isn't completely compatible with the way Briefcase packages Python. We've seen this with some numerical processing libraries, for example. This should be a solvable problem; but we need to narrow down a good solution.

The other possibility in this case is that the problem *might* be related to your locale - from the look of it, your locale is Greek? Apologies if I've got the language/country wrong - at the very least, it's not Latin/CP-1252. We haven't had any reports of issues with non-Latin locale issues - but I can't confirm it's known to work, either.

The best option at this point would be to manually start the app the same way that Briefcase does, and get the logs as the app crashes. From a fresh prompt in your project directory (but *don't* start the virtual environment), run:

    C:\...> "windows\Hello World\src\python\python.exe" -m helloworld

That *should* start the app; and if/when it fails, it should provide the stack trace for the failure.

**Comment by m1233** [comment]
To begin with, yes my locale is Greek and even if it wasn't no need to apologize. Second of all, my code is the exact same as in the tutorial apart from the message that appears in the command line when I press the button present in the program. I copy and pasted the command and this is what I got:

![Στιγμιότυπο οθόνης (166)](https://user-images.githubusercontent.com/38630937/106382089-dd73e800-63c5-11eb-837f-d72713c54931.png)

**Comment by freakboy3742** [comment]
Ah - I should have been more clear - you're trying to run the app, so you'll need to substitute the name of the module in that command - I assumed it would be `helloworld`, but if you used `hello_world`, you should use that instead.

**Comment by liudonghua123** [comment]
It seems the same with [mine](https://github.com/beeware/beeware/issues/53#issuecomment-876963916).

**Comment by liudonghua123** [comment]
> It seems the same with [mine](https://github.com/beeware/beeware/issues/53#issuecomment-876963916).

I have found mine issue was missing `briefcase create` before `briefcase run`, see https://github.com/beeware/beeware/issues/53#issuecomment-877900548.

**Comment by freakboy3742** [comment]
Closing due to a lack of response from the original reporter.
